import type { Metadata } from 'next';
import './globals.css';
import NavLinks from '../../components/dashboard/nav-links';
import { montserratFont } from '../../components/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserratFont.className}`}>
        <section className="mt-[30px] mb-[100px] mx-[30px]">{children}</section>
        <NavLinks />
      </body>
    </html>
  );
}
